relay-tools/react-relay-network-modern

src/middlewares/cache.js

The cacheConfig object (which is optional) can provide a flag to force refetches when a caching middleware is in place.
The config is used on QueryRenderers:
https://github.com/facebook/relay/blob/master/packages/react-relay/modern/ReactRelayQueryRenderer.js#L54
And in the options for a refetch inside a refetch container:
https://facebook.github.io/relay/docs/en/refetch-container.html#refetch

update cache middleware to respect cacheConfig

---

.eslintrc
README.md
src/RelayRequestBatch.js
src/definition.js
src/middlewares/__tests__/__snapshots__/url-test.js.snap
src/middlewares/__tests__/batch-test.js
src/middlewares/__tests__/url-test.js
src/middlewares/batch.js
src/middlewares/url.js

As discussed on https://github.com/nodkz/react-relay-network-modern/issues/15.
- add `credentials` option to batch middleware
- add `options: BatchFetchOpts` to RelayRequestBatch and spread it to fetchOpts

add credentials options to batch

---

README.md
src/middlewares/cache.js

Sometimes it is useful to just invalidate the entire cache when the user mutates the graph.

update cache middleware to optionally clear on mutation

---

README.md
src/middlewares/cache.js

It makes sense to avoid pulling from the cache for forced requests, but sometimes we want to configure the network layer to cache the response from forced requests.  This especially makes sense when we force a refresh on a page or screen, then navigate away from the screen and the component becomes unmounted. When someone returns to that screen, the QueryRenderer runs again, but this time it is not a forced request and the screen winds up fetching stale information.

Add flag to enable the caching of forced requests

---

README.md
src/RelayNetworkLayer.js
src/__tests__/fetchWithMiddleware-test.js
src/fetchWithMiddleware.js

Not sure if others are experiencing this issue but for me when the GraphQL server responds with errors, e.g.
```
{
"errors": [
{
"path": [
"signInUser"
],
"message": "Bad username or password.",
"locations": [
{
"line": 2,
"column": 0
}
]
}
],
"data": {
"signInUser": null
}
}
```
The exception thrown by RRNM is not catchable.
This PR allows an option to be set that disables throwing on errors, and moves responsibility of error handling to the calling code.

add noThrow option

---

README.md

If using with Webpack 4, make sure that project is equipped to parse .mjs files correctly. (If using Webpack 3, can omit the `module` definition.)
```javascript
module: {
rules: [
// See: https://github.com/aws/aws-amplify/issues/686#issuecomment-387710340
{
test: /\.mjs$/,
include: /node_modules\/react-relay-network-modern/,
type: 'javascript/auto',
},
]
},
resolve: {
extensions: ['.mjs', '.js']
}
```

[Docs] Add note about Webpack

---

README.md
src/__mocks__/mockReq.js
src/middlewares/__tests__/cache-test.js
src/middlewares/cache.js

Currently the cache middleware is caching any response, even it has a error.
This PR fix it.

[cacheMiddleware] Do not cache responses with errors

---

README.md
src/middlewares/__tests__/retry-test.js
src/middlewares/retry.js

Hello all,
My company has been religiously using this package for a while, but a new need has come up for us to be able to dynamically compute the timeout value to account for possible transient errors on our backend services.  This has been a huge component for us and I'm happy to be able to provide this functionality back to the community for others whom may also need this.
Please let me know what I can do to get this PR into a shape to be merged or whether this feature would ultimately be rejected.
Thanks so much for taking a look!

RetryMiddleware: Allow fetchTimeout to be a function similar to retryDelays

---

src/__tests__/fetchWithMiddleware-test.js
src/createRequestError.js
src/middlewares/__tests__/retry-test.js

When the SSR middleware creates a response object [here](https://github.com/relay-tools/react-relay-network-modern-ssr/blob/0c111652cdee1882dd03d4e0cae69111c8c09f88/src/server.js#L73), the response object will not have a `.json` property, but it will have `.data` and/or `.errors` properties. Without this change the actual underlying GraphQL error would not get surfaced, instead it would always go into the `!res.json` branch.
Also see https://github.com/artsy/force/pull/3261

Surface errors from SSR middleware

---

src/middlewares/__tests__/auth-test.js
src/middlewares/auth.js

* reset `tokenRefreshInProgress` to `null` when refresh token failed
fix: #50

fix(authMiddleware): reset refresh token state

---

README.md
src/middlewares/__tests__/retry-test.js
src/middlewares/retry.js

* support aborted with custom message in beforeRetry
if pass msg to `abort` will throw Error with the passed msg
else use default msg
* add new type `AbortFn`
fix: #53

feat(retryMiddleware): aborted with custom message

---

src/RelayNetworkLayer.js
src/__mocks__/mockReq.js
src/definition.js
src/middlewares/__tests__/__snapshots__/auth-test.js.snap
src/middlewares/__tests__/__snapshots__/batch-test.js.snap
src/middlewares/__tests__/__snapshots__/logger-test.js.snap
src/middlewares/__tests__/__snapshots__/perf-test.js.snap
src/middlewares/__tests__/__snapshots__/retry-test.js.snap
src/middlewares/__tests__/__snapshots__/url-test.js.snap
src/middlewares/logger.js

Returning an "observable" instead of a promise enables support for cancelling requests, `commitMutation` for example, by calling `dispose()` on the returned object.
Also added a message to logger for when a request is cancelled.
Not sure if this also solves #40, I do not have a test for that.
Uses AbortController for fetch cancellation which is supported in most modern browsers.
Note: Depending on when the request is cancelled the server might still apply the changes of a mutation.

Add cancel functionality to requests

---

src/RelayRequest.js

This fixes using the library in non-browser environments. Not sure why this is on `window` -- should probably also check `global`, similar to `getFormDataInterface`?

Check for `window`

---

package.json
yarn.lock

Updates the Relay dependency to v4.0.0. It might also work to make the version `>= 3.0.0` since there were no breaking changes for this package. Any opinions?

Update to relay-runtime v4.0.0

---

README.md
package.json
src/index.js
src/middlewares/__tests__/__snapshots__/batch-test.js.snap
src/middlewares/__tests__/__snapshots__/legacyBatch-test.js.snap
src/middlewares/__tests__/batch-test.js
src/middlewares/__tests__/legacyBatch-test.js
src/middlewares/batch.js
src/middlewares/batchLegacy.js
src/middlewares/legacyBatch.js
yarn.lock

* Tracks batch requests in Array instead of Map #31
* Determines duplicate requests based on body of request (which includes the request ID) #31, #48

Batch request list as array & check duplicates comparing body

---

src/index.d.ts

Fix type definitions for ...
- RelayRequest  => RelayNetworkLayerRequest 
- RelayResponse => RelayNetworkLayerResponse
- RelayRequestBatch  => RelayNetworkLayerRequestBatch 
Because it was renamed in [index.js](https://github.com/relay-tools/react-relay-network-modern/blob/2ca12a2111485f9212ca8d4150e4e45bc39d9379/src/index.js#L15-L17)

Fix type definitions for re-exported class

---

src/index.d.ts

Sorry about [Fix type definitions for re-exported class #68](https://github.com/relay-tools/react-relay-network-modern/pull/68), i just renamed those.
I modified the things that i had just renamed with re export.

Fix type definitions for re-exported class. (again)

---

src/RelayNetworkLayer.js
src/__tests__/RelayNetworkLayer-test.js

Polling in relay is implemented by resubscribing to the observable so we need to make sure to create a new request each time otherwise stale data is returned (see https://github.com/facebook/relay/blob/aef8a5e33763e9d9a4e1e294913cbdbdb5634ecc/packages/relay-runtime/network/RelayObservable.js#L398).
This also fixes tests since network.execute returns an Observable and not a Promise.

Fix request polling

---

src/RelayRequest.js
src/__mocks__/mockReq.js
src/middlewares/__tests__/__snapshots__/logger-test.js.snap
src/middlewares/__tests__/__snapshots__/perf-test.js.snap

Using the query text to check if a request is a mutation doesn't work when using persisted queries since the query text will be empty. Instead we can use `operation.operationKind` which is always set properly.

Fix `isMutation` when using persisted queries

---

src/definition.js

Fix those error:
```sh
Error ┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈ node_modules/react-relay-network-modern/lib/RelayRequest.js.flow:101:27
Cannot get this.operation.operationKind because property operationKind is missing in ConcreteBatch [1].
[1]  15│   operation: ConcreteBatch;
:
98│   }
99│
100│   isMutation(): boolean {
101│     return this.operation.operationKind === 'mutation';
102│   }
103│
104│   isFormData(): boolean {
Error ┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈ node_modules/react-relay-network-modern/node8/RelayRequest.js.flow:101:27
Cannot get this.operation.operationKind because property operationKind is missing in ConcreteBatch [1].
[1]  15│   operation: ConcreteBatch;
:
98│   }
99│
100│   isMutation(): boolean {
101│     return this.operation.operationKind === …
```

fix(definition): fix flow type error

---

package.json
src/RelayNetworkLayer.js
src/middlewares/cache.js
yarn.lock

- ⚡️ make react-relay an optional dep
This package supports being used by a nodeJS project to support batching. Having react-relay as a peer dependency causes a waring in nodeJS projects that don't have/require react-relay.

⚡️ make react-relay an optional dep

---

package.json

I just ran into an issue when trying to use the network layer and it turns out [.mjs is not supported anymore](https://twitter.com/dan_abramov/status/1042884207666704390?lang=en) in `create-react-app`. Since CRA is so widespread thoughts on removing it? 
(I've also noticed other problems with .mjs and webpack [as seen here](https://github.com/artsy/force/blob/master/webpack/envs/baseConfig.js#L50-L55).)

Remove .mjs to support Create React App

---

README.md
package.json
src/index.d.ts
src/index.js
src/middlewares/upload.js
yarn.lock

Opened this per @nodkz's request: https://github.com/relay-tools/react-relay-network-modern/issues/41#issuecomment-513845572
We have been using this for a few months with [graphql-upload](https://github.com/jaydenseric/graphql-upload) on the backend.
We've used this:
- with Relay 5, 6, 7 and experimental 
- on both React and React Native
- with react-relay HOCs, unofficial [relay-hooks](https://github.com/relay-tools/relay-hooks) and official experimental hooks

feat: add upload middleware

---

package.json
yarn.lock

I don't know if this optional dependency is required, but I suspect not. Anyone using Relay with TypeScript has almost certainly added `@types/relay-runtime` directly as a dependency or dev dependency in their own `package.json`. Since this project isn't really bound to much of Relay's internals, it doesn't need to be updated at the same frequency as `@types/relay-runtime`. By listing `@types/relay-runtime` as an optional dependency of this project, however, it will forever be in conflict with anyone needing a different version of `@types/relay-runtime` (see #81).

Remove unnecessary optional dependency.

---

src/index.d.ts

The `Headers` type was not being exported in the TypeScript definition, so there ways no good way of creating the headers. This PR exposes the type and makes it clear that `FetchOpts#headers` should use that newly exposed type. The change makes the type equivalent to the Flow version exposed elsewhere in the code.

Expose the `Headers` type so it can be used in the URL middleware.

---

src/index.d.ts

I believe this PR brings the TypeScript definition of `RelayResponse` up to date with the Flow definition, fixing #86. For the most part, I just added the missing fields and functions. I did re-type `json` from `any` to `unknown` to better match the semantics of the Flow definition. If this problematic, I back that out again.
I also left the type of `ok` as `any` to match the Flow definition, but I've only ever seen it being a `boolean`. Can it be anything other than a boolean value? If so, could it be better be represented as a union type rather than `any`?

Update TypeScript definition of `RelayResponse` to match Flow definition.

---

src/RelayResponse.js
src/index.d.ts
src/index.js

I don't know if you really want to expose this functionality or not, but it helps me address the problem I raised in #88. With this change, I can add custom middleware to do the following:
```
next => async req => {
Sentry.setTag('graphql_query', req.getID())
try {
const res = await next(req)
if (res.errors) {
const error = createRequestError(req, res)
Sentry.captureException(error)
}
return res
} catch (e) {
Sentry.captureException(e)
throw e
}
}
```
Or:
```
next => async req => {
Sentry.setTag('graphql_query', req.getID())
try {
const res = await next(req)
if (res.errors) {
const errorMessage =
req instanceof RelayNetworkLayerRequest
? formatGraphQLErrors(req, res.errors)
: JSON.stringify(res.errors)
Sentry.captureMessage(errorMessage)
}
return res
} catch (e) { …
```

Expose error creation functions

---

src/middlewares/batch.js
src/middlewares/retry.js

When a request is canceled, the `AbortError` bubbles up and both the `batch` and `retry` middlewares don't let it continue to bubble up.

Handle canceled requests better

---

src/__mocks__/mockReq.js
src/definition.js
src/middlewares/__tests__/batch-test.js
src/middlewares/batch.js

When `cacheConfig.skipBatch` is truthy, we skip batching for that request even when the batchMiddleware is present. This allows users to better control what requests are batched together.
Use case: 
We have a bunch of `QueryRenderer`s on the page at once. Some of those queries are very fast, but a couple of them are very slow. When they're all batched together those fast queries are now just as slow as the slowest query in the batch. This allows us to skip batching for those very fast queries so that user's get a snappier experience.
Fixes #80 
This is my first PR on this project so please let me know what I may have missed or what I can do to further help!

Add `skipBatch` to cacheConfig options

---

src/index.d.ts

Adds the [`operationKind`](https://github.com/relay-tools/react-relay-network-modern/blob/488944f89f40639e9c87319363709c68f366e312/src/definition.js#L85) property which was missing.

Adds the operationKind property to ConcreteBatch type

---

README.md

Relating to #69 
Adding README information, as this will potentially affect any newcomers.
I am not 100% sure which import should be used or whether core-js should be installed (rather than attempting to import one of the other imports) as I am relatively new to the JS world

Adding information regard #69 (Cannot find module 'core-js')

---

src/RelayNetworkLayer.js
src/index.d.ts

RelayNetworkLayerOpts should be exposed externally so that wrapper application can simply extend the type.
Currently, types have to be copied from the package and into the application

Exporting RelayNetworkLayerOpts to be used externally

---

src/index.d.ts

The old `QueryResponseCache` wasn't correct.
I think we should keep the export for now, otherwise it can be a breaking change.

Fix cache onInit typings

---

src/express-middleware/graphqlBatchHTTPWrapper.js
src/index.d.ts

Two minor changes here concerning `graphqlBatchHTTPWrapper`
* We want to spread the existing `res` so as to not lose any thing that is, for instance, stored on `res.locals` which middleware up the stack might stick on the response.
* Exposes its TS type

graphqlBatchHTTPWrapper

---

src/createRequestError.js

This seemingly was introduced in a9a036ff1a02f0be5e9fe9b667b1bf2ec6a2d2b8. Persisted queries do not have a query body, and therefore the `queryLine.subtr` later on fails.
To fix this, I only applied the error locations mapping when there are queryLines present.

Fix formatGraphQLErrors for persisted queries

---

README.md
src/index.d.ts
src/middlewares/__tests__/cache-test.js
src/middlewares/cache.js

Add `updateTTLOnGet` argument to cache middleware to reset the TTL on cache payloads when fetched from cache
It is sometimes desired to keep items in cache for extended periods of time, longer than the typical TTL without refetching them after the first fetch.
cc @nodkz

Add `updateTTLOnGet` argument to cache middleware 

---

src/middlewares/error.js

In `middlewares/error.js` `noticeAbsentStack` function, it return a string with stack: `process.env.NODE_ENV`.
When using the packages with vitejs, it will automatically replace the `process.env.NODE_ENV` string with something like this `"development"`, which cause `Uncaught SyntaxError: Unexpected identifier error`.
more details here: https://vitejs.dev/guide/env-and-mode.html#env-variables
Suggested by vitejs, we can break the string up with a unicode zero-width space, e.g. `'import.meta\u200b.env.MODE'`

escape process.env.NODE_ENV to solve the error when using with vitejs
